### ISSUE TITLE
Factory reset may not be needed

### ISSUE THREAD

**Issue by danieleds** [alexhorn/laemp#1]
Hey, a week ago in my spare time I started doing the same thing that you're doing. I am using different technologies (such as pygatt) but I see that we have started from the self-same resources.

During my own research I have noticed something that I have not found written anywhere, so I thought I would share it. If you open the Hue BT app, then go to Settings -> Voice Assistants -> [Pick one assistant] -> Click on "Make visible", then the bulb can be paired. At that point you will be able to control the bulb from both the smartphone *and* the pc.

I have only tested this on one bulb so I'm not sure how much it is reliable. If you can try it yourself, let me know

**Comment by alexhorn** [comment]
That's a great tip, thank you! I just tried it with my Hue Go (LCT026) and it works. Now both my Raspberry Pi and my computer are paired with the light, which makes debugging quite a bit easier.
